-- Consolidate life-stage organizing offers. Preserve historical product records and URLs.
BEGIN;
INSERT INTO public.products (id,name,category,description,order_mode,order_code,fixed_config,external_link_config,checklist,image) VALUES ('organizing','老前整理','老前整理','在人生的重要時刻，陪您整理空間、保存回憶，安排下一段生活','EXTERNAL_LINK','ORGA','{"price": 0, "unit": "次", "buttonText": ""}'::jsonb,'{"priceText": "依整理範圍評估報價", "buttonText": "Line 報價預約", "url": "https://line.me/R/ti/p/@021souxl"}'::jsonb,'[{"text": "物品分為「留／傳／贈／離」四類"}, {"text": "重要文件整理，方便日後尋找"}, {"text": "紀念物拍照建檔，留下您的故事"}, {"text": "可銜接整戶清空與清運"}]'::jsonb,'/images/uniforms/scene-94.webp') ON CONFLICT (id) DO NOTHING;
INSERT INTO public.pages (id,slug,title,template,content,is_published) VALUES ('organizing','services/organizing','老前整理','SUB_ITEM','{"hero": {"title": "老前整理", "description": "在人生的重要時刻，陪您整理空間、保存回憶，安排下一段生活", "backgroundImage": "", "mainButton": {"text": "安心顧問諮詢", "type": "URL", "value": "/consultant", "isVisible": true}, "secondaryButton": {"text": "", "type": "URL", "value": "", "isVisible": false}}, "services": [], "cases": [], "showForm": false, "subItem": {"productId": "organizing", "linkedProductId": "organizing", "hideProductMainImage": true, "mainTitle": "老前整理", "coreServicesSectionTitle": "從了解需求，到一起完成", "coreServices": [{"title": "01 評估", "content": "安心顧問先了解您的需求、空間與希望的節奏。"}, {"title": "02 報價", "content": "說明服務範圍、時程與費用，經您確認後安排。"}, {"title": "03 整理", "content": "依約定範圍執行；物品處置前先取得同意。"}, {"title": "04 交付", "content": "一起核對整理結果與物品紀錄，討論後續安排。"}], "partners": [], "cases": [], "faqs": [{"id": "organizing-price", "question": "不同整理目標，收費方式不同嗎？", "answer": "退休整理、老前整理、遺物整理與搬家整理，都是同一項服務，使用相同計價方式。實際費用依整理範圍、物品量、人力與時程評估，先確認報價再安排。"}], "additionalServices": ["vacant-property", "removal"], "button": {"text": "Line 報價預約", "type": "URL", "value": "https://line.me/R/ti/p/@021souxl", "isVisible": true}, "serviceIntro": {"sections": [{"id": "organizing-intro", "type": "TEXT", "text": {"content": "## 可陪您做的事\n\n- 物品分為「留／傳／贈／離」四類\n\n- 重要文件整理，方便日後尋找\n\n- 紀念物拍照建檔，留下您的故事\n\n- 可銜接整戶清空與清運\n\n## 依您的節奏安排\n\n**陪伴型**：慢慢做，與家人一起討論物品和居住安排。\n\n**效率型**：您已決定範圍與物品去留，由我們依約定時程執行。\n\n先評估再報價，第一次到府免費。後續服務範圍與費用，經您確認後才安排。", "alignment": "left", "fontSize": "body"}}]}}}'::jsonb,true) ON CONFLICT DO NOTHING;
UPDATE public.products SET external_link_config=COALESCE(external_link_config,'{}'::jsonb)||jsonb_build_object('priceText','依整理範圍評估報價') WHERE id IN ('life-organizing','retirement-organizing','estate-organizing') AND order_mode='EXTERNAL_LINK';
UPDATE public.pages SET is_published=false WHERE id IN ('life-organizing','retirement-organizing','estate-organizing');
UPDATE public.pages SET content=replace(content::text,'"life-organizing"','"organizing"')::jsonb WHERE id IN ('vacant-property','removal') AND content::text LIKE '%life-organizing%';
-- Keep a valid public source before frontend rollout; the brand resolver serves the reviewed edit.
UPDATE public.products SET image='https://dmuqabrxzoctalflljcz.supabase.co/storage/v1/object/public/media/uploads/1777883547445-__.jpg' WHERE id='organizing' AND image='/images/uniforms/scene-94.webp';
COMMIT;
